### ISSUE TITLE
Naszekino online

### ISSUE THREAD

**Issue by zbigzbig20** [meserak86/cimar#1]
Hi. Możesz jeszcze dodać ten dodatek wideo bo jego tylko brakuje. Pozdro

**Comment by meserak86** [comment]
repozytorium zostaje w takim ksztalcie i ilosci wtyczek do momentu dopuki dziala, wszelkie zmiany uzaleznione beda od tego czy dostaniemy nowsza wersje repo czy nie, a nie wiadomo czy i kiedy to bedzie, ale raczej nigdy, tak czy siak  z tego co widze incursion bedzie dodawac zrodla w koncu glowny swolowers ramica tomasiek zalizuje tez w incursion, zaforkowal moje repo i nagle tydzien pozniej pokazal sie segos.se jako zrodlo w incursion:D ( mnie osobiscie to cieszy, a jego osoba smieszy:D)
ANALIZUJAC RAMIC REPO:
ramic to 40+ wtyczek z czego 20 - polowa wtyczek to filmy i seriale a reszta to wtyczki po 2 z kazdego typu kontentu pozostalego, tak naprawde te 20 filmowo serialowych wtyczek zastapi ci incursion + phantom-CDA, z takiego bardziej pozadanego kontentu zostaje sport - ramicowska ekstraklasa, a reszta wtyczek to rozrywka typu kabarety- od tego masz youtube, anime nikt prucz mnie nie oglada, ta jego wtyczka jest stara, bajki sa 2 wtyczki i obie sa MARNE jesli chodzi o ilosc zrodel itd, 3 wtyczki dokumentalne, muzyczne itd... to wszystko ci zalatwia youtube i odpowiednie playlisty... osobiscie nic nie znajduje ciekawego w repo ramica i nie bede po nim plakal, ci co placza powinni przetrzec oczy to zobacza ze sa lepsze alternatywy

**Comment by zbigzbig20** [comment]
Generalnie z repo ramica używałem alltube cda i naszekino online. Było to tylko uzupełnienie do dawnego genesisa i jego forków skończywszy na incursion. Płakał nie będę po ramicu bo jest w czym jeszcze przebierać. Reszta contentu jaką oferował ramic była dla mnie zbedna. Do live tv i sportu mam tuner sat z nc+ i cp na którym to mam zainstalowany libreelec. Żeby nie było to także lubię anime i do dziś oglądam dragon ball (zawsze aktualny odcinek co niedzielę na yt) . Resztę w razie czego załatwia netflix :-) Problem z nasze kino online rozwiązałem. Miałem zipa z jego ostatnią wersją 2.5 , zainstalowalem i działa. Moja druga połowa będzie happy bio to ona głównie z tej wtyczki korzystała

**Comment by meserak86** [comment]
Sie zobaczy, ramic to nie konic swiata, moze sie cos ruszy na polskiej scenie kodi i te koleczka rozancowe sie troche zmienia... ja walcze o zaprzestanie robienia z kodi i wiedzy o nim tematu dla wybranych grup... robie tutoriale na YT by kazdy mogl sobie cos podlubac w temacie kodi dlatego mnie tak wszyscy nienawidza, bo nie bawie sie w robienie papierzakow tylko wykarczowuje krzaki by kazda dupa jak oddaje K byla widoczna, by bylo wiadomo kto puscil kleksa i w ktorym miejscu:D
