### ISSUE TITLE
Jak pobrać?

### ISSUE THREAD

**Issue by rafciu27** [meserak86/cimar#3]
Jak pobrać repozytorium 1.3.9? Adres ramic/repository.ramic/repository.ramic-1.3.9.zip nie działa.

**Comment by Andrewkospl** [comment]
Wrzuć zip-a na dysk i instalacja lokalna :)

https://github.com/meserak86/cimar/blob/master/repository.ramic-1.3.9.zip

**Comment by frijerz** [comment]
Czy to jest ta wersja "oczyszczona" i bezpieczna? Nie korzystam z buildow, pytam z ciekawosci.
